os_login: admin
os_password: **#!@#$%^^&&*
os_tenant_name: demo
auth_url: http://172.16.140.246:5000/v2.0
image_id: 60ba0c15-eb47-47f8-8b5f-c6b8d2fa6018
flavor_id: 101
key_name: cloudkey
multinic: false
