# Creates a new VM and attaches to a network and passes metadata to the instance
#- include_vars: vars.yml

- nova_compute:
      state: present
      login_username: "{{ os_login }}"
      login_password: "{{ os_password }}"
      login_tenant_name: "{{ os_tenant_name }}"
      auth_url: "{{ auth_url }}"
      name: "{{ instance_name }}"
      image_id: "{{ image_id }}"
      flavor_id: "{{ flavor_id }}"
      key_name: "{{ key_name }}"
  register: devstack_instance

- name: output info
  debug: var=devstack_instance['private_ip']

- name: Add to devstack_instances
  add_host: hostname={{ devstack_instance['private_ip'] }} groupname=devstack_instances

- name: wait for ssh to be ready
  wait_for:
    port: 22
    host: "{{ devstack_instance['private_ip'] }}"
    timeout: 120
    state: started

- name: pause for 30 seconds
  pause: seconds=30
