- hosts: devstack_instances
  tasks:

  - name: send over rootwrap
    sudo: yes
    template: src=../../templates/compute.filters dest=/etc/nova/rootwrap.d/compute.filters

  - name: run tempest
    sudo: no
    sudo: no
    shell: tools/pretty_tox.sh volume | tee -a console.log.out
    args:
      chdir: /opt/stack/tempest
